[package]
name = "rustyboy"
version = "0.1.0"
authors = ["JoÃ£o Delgado <joaomtdelgado@gmail.com>", "Tiago Marques <samarques.tiago@gmail.com>"]

[dependencies]

[[bin]]
name = "rustyboy"
doc = false


[features]
debug = [] # feature has no explicit dependencies